# File: config/data_sources/joke_api_test.yaml
data_source:
  name: "joke_api_test"
  type: "rest_api"
  endpoint: "https://official-joke-api.appspot.com/jokes/programming/random"
  authentication:
    type: "none"  # No authentication needed for this API
  request_config:
    method: "GET"
    timeout: 10
    retry_count: 2
    headers:
      Accept: "application/json"

validation_rules:
  - field: "setup"
    type: "string"
    max_length: 500
    required: true
  - field: "punchline"
    type: "string"
    max_length: 500
    required: true
  - field: "type"
    type: "string"
    required: true

transformation:
  column_types:
    setup: "string"
    punchline: "string"
    type: "string"
    id: "int"
  
  new_columns:
    setup_upper: "setup.str.upper()"
    punchline_upper: "punchline.str.upper()"
    full_joke: "setup_upper + ' -- ' + punchline_upper"
    joke_length: "setup.str.len() + punchline.str.len()"
    processed_at: "pd.Timestamp.now()"
  
  filters:
    joke_length: "> 10"  # Only jokes longer than 10 characters

# No enrichment needed for this test
enrichment: []

destination:
  primary:
    type: "print_logs"
    max_rows: 20
  
  backup:
    type: "local_file"
    path: "/tmp/airflow_output"
    filename: "joke_api_data"
    format: "csv"
  
  archive:
    type: "local_file"
    path: "/tmp/airflow_output/archive"
    filename: "joke_api_archive"
    format: "json"

schedule:
  interval: "*/10 * * * *"  # Every 10 minutes for testing
  start_date: "2024-01-01"
  catchup: false
  tags: ["test", "joke_api", "development"]